# Generated by Django 2.1.2 on 2018-10-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=50)),
                ('email_contact', models.CharField(max_length=30)),
                ('phone_contact', models.CharField(max_length=30)),
                ('contact_sent_date', models.CharField(max_length=30)),
            ],
        ),
    ]
