# Generated by Django 2.1.2 on 2018-10-16 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181016_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_sent_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
        ),
    ]
