# Generated by Django 2.1.2 on 2018-10-20 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181018_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=35),
        ),
    ]
